I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 79, in script
    # add a file (named either "bg room.png" or "bg room.jpg") to the
  File "renpy/common/00action_file.rpy", line 458, in get_sensitive
    return renpy.can_load(__slotname(self.name, self.page, self.slot))
  File "renpy/common/00action_file.rpy", line 131, in _m1_00action_file__slotname
    page = int(page)
TypeError: 'int' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 79, in script
    # add a file (named either "bg room.png" or "bg room.jpg") to the
  File "C:\Users\steve\Downloads\RenPy\renpy-7.3.5-sdk\renpy\ast.py", line 708, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\steve\Downloads\RenPy\renpy-7.3.5-sdk\renpy\exports.py", line 1345, in say
    who(what, *args, **kwargs)
  File "C:\Users\steve\Downloads\RenPy\renpy-7.3.5-sdk\renpy\character.py", line 1142, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "C:\Users\steve\Downloads\RenPy\renpy-7.3.5-sdk\renpy\character.py", line 842, in do_display
    **display_args)
  File "C:\Users\steve\Downloads\RenPy\renpy-7.3.5-sdk\renpy\character.py", line 591, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Users\steve\Downloads\RenPy\renpy-7.3.5-sdk\renpy\ui.py", line 297, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\steve\Downloads\RenPy\renpy-7.3.5-sdk\renpy\display\core.py", line 2702, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\Users\steve\Downloads\RenPy\renpy-7.3.5-sdk\renpy\display\core.py", line 3094, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "C:\Users\steve\Downloads\RenPy\renpy-7.3.5-sdk\renpy\display\core.py", line 541, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\steve\Downloads\RenPy\renpy-7.3.5-sdk\renpy\display\core.py", line 541, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\steve\Downloads\RenPy\renpy-7.3.5-sdk\renpy\display\core.py", line 541, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\steve\Downloads\RenPy\renpy-7.3.5-sdk\renpy\display\screen.py", line 434, in visit_all
    self.child.visit_all(callback, seen=None)
  File "C:\Users\steve\Downloads\RenPy\renpy-7.3.5-sdk\renpy\display\core.py", line 541, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\steve\Downloads\RenPy\renpy-7.3.5-sdk\renpy\display\core.py", line 541, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\steve\Downloads\RenPy\renpy-7.3.5-sdk\renpy\display\core.py", line 543, in visit_all
    callback(self)
  File "C:\Users\steve\Downloads\RenPy\renpy-7.3.5-sdk\renpy\display\core.py", line 3094, in <lambda>
    root_widget.visit_all(lambda i : i.per_interact())
  File "C:\Users\steve\Downloads\RenPy\renpy-7.3.5-sdk\renpy\display\behavior.py", line 862, in per_interact
    if self.is_sensitive():
  File "C:\Users\steve\Downloads\RenPy\renpy-7.3.5-sdk\renpy\display\behavior.py", line 850, in is_sensitive
    return is_sensitive(self.action)
  File "C:\Users\steve\Downloads\RenPy\renpy-7.3.5-sdk\renpy\display\behavior.py", line 411, in is_sensitive
    return action.get_sensitive()
  File "renpy/common/00action_file.rpy", line 458, in get_sensitive
    return renpy.can_load(__slotname(self.name, self.page, self.slot))
  File "renpy/common/00action_file.rpy", line 131, in _m1_00action_file__slotname
    page = int(page)
TypeError: 'int' object is not callable

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Love Takes Flight prealpha0.1
Thu Dec 10 14:34:07 2020
